#!/bin/bash
# Creates a new branch in svn, using the current trunk.
# Two obligatory argument:
# 1) name of branch (like new_feature)
# 2) commit message (a short description of the branch)

# Test arguments
if [ $# -ne 2 ]; then
  echo "ERROR: requires 2 arguments"
  exit 1
fi

# define variables
URL="https://a-dda.googlecode.com/svn"
branchname="$1"
branchURL="$URL/branches/$branchname"

# create new branch
svn copy -m "$2" "$URL/trunk" "$branchURL"
if [ $? -ne 0 ]; then
  echo "ERROR: svn copy failed"
  exit 1
fi
