#!/bin/bash

if [ -z "${ADDABIN}" ]; then
 export ADDABIN=../../../src/adda
fi
if [ -z "${MPIEXEC}" ]; then
 export MPIEXEC="mpirun -np 4"
fi

for j in *; do
  if [ -d $j ]; then 
  echo "*****************************"
  echo " Running Test " $j
  echo "*****************************"
  cd $j
  ./run
  cd ..
  fi
done
