#!/bin/bash

# SET YOUR PATH:
path="./"

# SET YOUR PARAMETERS (now the parameters are set for Figure 16 [c] from the paper):
size=500
m=1.1
mi=0
g=800
eps=6
chptime=60h
type=wkbr
qsub -v size=$size,m=$m,mi=$mi,grid=$g,eps=$eps,callnum=1,time=$chptime,type=$type $path/batch
qsub -v size=$size,m=$m,mi=$mi,grid=$g,eps=$eps,callnum=2,time=$chptime,type=$type $path/batch
qsub -v size=$size,m=$m,mi=$mi,grid=$g,eps=$eps,callnum=3,time=$chptime,type=$type $path/batch
qsub -v size=$size,m=$m,mi=$mi,grid=$g,eps=$eps,callnum=4,time=$chptime,type=$type $path/batch
