#!/bin/bash
# Creates a new (version) tag in svn, using the current trunk.
# Single obligatory argument - name of version (like 1.0)

# Test arguments
if [ $# -ne 1 ]; then
  echo "ERROR: requires 1 arguments"
  exit 1
fi

# define variables
URL="https://a-dda.googlecode.com/svn"
tagname=rel_"$1"
tagURL="$URL/tags/$tagname"

# create new tag
svn copy -m "new release $1" "$URL/trunk" "$tagURL"
if [ $? -ne 0 ]; then
  echo "ERROR: svn copy failed"
  exit 1
fi
