#!/bin/sh
# This is sample batch file to run ADDA using SGE
# it was designed for DAS-3 cluster
# (http://www.cs.vu.nl/das3/)
# Auth: Adianto Wibisono
#
# Choose shell
#$ -S /bin/sh
# Work from the current working directory
#$ -cwd
# Name of the job
#$ -N ADDA
# Set requested execution time
#$ -l h_rt=0:15:00
# Set parallel environment and number of nodes 
#   (number of processors is a multiple of that number)
#$ -pe mpich 4
# Merge stderr with stdout
#$ -j yes

PROG=adda_mpi
ARGS=""

# The number of cores per node can be different on the various DAS sites.
# Here we will use every cpu core there is on the first compute node,
# and assume this will be the same on the other nodes in the same cluster:
cpuspernode=`cat /proc/cpuinfo | grep processor | wc -l`
ncpus=`expr $NSLOTS \* $cpuspernode`

export MPICH_PROCESS_GROUP=no
. /etc/profile.d/modules.sh
module add default-ethernet  # or "default-myrinet"

#$ -v MPI_HOME
#$ -v LD_LIBRARY_PATH

echo "Got $NSLOTS nodes."
echo "Original machines file:"
cat $TMPDIR/machines
for i in `cat $TMPDIR/machines`; do
    j=0
    while [ $j -lt $cpuspernode ]; do
        echo $i
        j=`expr $j + 1`
    done
done > $TMPDIR/machines2
echo "Using following machines file:"
cat $TMPDIR/machines2

cmd="$MPI_HOME/bin/mpirun -np $ncpus -machinefile \
$TMPDIR/machines2  $PROG $ARGS"
echo Will run: $cmd
$cmd
