#!/bin/bash
# Assumes that a new tag in git has been allready created.
# Then creates the ADDA package excluding all git and GitHub auxiliary files entries. Win64 files are zipped separately.
# Single obligatory argument - name of version (like 1.4.0)
#
# !!! We are still struggling to produce correct LF line endings in the main source package, when archiving it on Windows
# Until this is solved, it is recommende to run the last command on Unix system

#Test arguments
if [ $# -ne 1 ]; then
  echo "ERROR: requires 1 argument"
  exit 1
fi
 
cd ..
git archive -o adda_${1}_win64.zip v$1:win64 --prefix win64/
git archive -o adda_${1}.zip v$1
# -c core.eol=lf