# Makefile for sequential version of ADDA package
# All options are defined in Makefile
# $Date::                            $
#
# Copyright (C) 2010-2011,2013,2014 ADDA contributors
# This file is part of ADDA.
#
# ADDA is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# ADDA is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with ADDA. If not, see
# <http://www.gnu.org/licenses/>.

# !!! This file do not have any options designed to be changed by ADDA user

CSOURCE += matvec.c

PROG   := $(PROGSEQ)
MYCC   := $(CC)
MYCF   := $(CF)
MYCCPP := $(CCPP)

include $(COMMONMK)
