#!/bin/bash

# The following script will locate adda (often out of the box), but you can override it by setting ADDA_SEQ
# explicitly here (uncomment the following line) or somewhere in the environment (the script will return this variable)
#export ADDA_SEQ="../../../src/seq/adda"
ADDA_SEQ=$(../../../examples/find_adda)
if [ $? -ne 0 ]; then
  exit 1
fi
# cannot be combined with variable setting above, since it will lose the exit code of find_adda
export ADDA_SEQ

if [ -z "${MPIEXEC}" ]; then
  which mpiexec > /dev/null 2>&1 # test availability of mpiexec
  if [ $? -eq 0 ]; then
    export MPIEXEC="mpiexec -n 4"
  else
    export MPIEXEC=""
  fi
fi

for j in *; do
  if [ -d $j ]; then 
  echo "*****************************"
  echo " Running Test " $j
  echo "*****************************"
  cd $j
  ./run
  cd ..
  fi
done
