#!/bin/bash

# The following script will locate adda (often out of the box), but you can override it by setting ADDA_SEQ
# explicitly here (uncomment the following line) or somewhere in the environment
#ADDA_SEQ="../../../src/seq/adda"
if ! . ../../../examples/find_adda.sh; then
  exit 1
fi

if [ -z "${MPIEXEC}" ]; then
  which mpiexec > /dev/null 2>&1 # test availability of mpiexec
  if [ $? -eq 0 ]; then
    export MPIEXEC="mpiexec -n 4"
  else
    export MPIEXEC=""
  fi
fi

for j in *; do
  if [ -d $j ]; then 
  echo "*****************************"
  echo " Running Test " $j
  echo "*****************************"
  cd $j
  ./run
  cd ..
  fi
done
