#!/bin/bash
echo '------------adda----------------'
$ADDABIN -eps 9 -store_beam -store_dip_pol -store_int_field -save_geom -dir . -prop 0 1 0 -pol cm -lambda 0.500 -m 0.5 3.0 -shape box 2 3 -grid 11 &> adda.out
ERR=$?
if [ $ERR -ne 0 ]; then
  echo "ADDA returned error $ERR"
  exit $ERR
fi
#grep "#@#" adda.out > commvar
mv box.geom target
echo '------------gendip--------------'
../../gendip > gendip.out
echo '------------genplane------------'
cat >plane_input_xy <<%EOF%
   15.0 3
   -10.0 30.0 40
   -10.0 30.0 40
%EOF%
../../genplane < plane_input_xy > plane_points_xy
echo '------------nearfield y------------'
cat >input_xy <<%EOF%
DIPY.SAV
500            ! lambda
plane_points_xy
nearfieldY_xy
1 !eincflag
0 !iformat
2 !debug
0 !internal
%EOF%
cp commvar.y commvar
$MPIEXEC ../../nearfield < input_xy > nearfieldy.out
echo -------------verifying--y-----------
../../checknfsymm < input_xy > checknfsymmy.out

echo '------------genplane------------'
cat >plane_input_yz <<%EOF%
   5.0 1
   -10.0 40.0 50
   -10.0 40.0 50
%EOF%
../../genplane < plane_input_yz > plane_points_yz
echo '------------nearfield x------------'
cat >input_yz <<%EOF%
DIPX.SAV
500            ! lambda
plane_points_yz
nearfieldX_yz
1 !eincflag
0 !iformat
2 !debug
0 !internal
%EOF%
cp commvar.x commvar
$MPIEXEC ../../nearfield < input_yz > nearfieldx.out
echo -------------verifying--x-----------
../../checknfsymm < input_yz > checknfsymmx.out

grep ERROR gendip.out                     > err.dat
grep ERROR nearfieldx.out   | grep -v _SY >> err.dat
grep ERROR checknfsymmx.out | grep -v _SY >> err.dat
grep ERROR nearfieldy.out   | grep -v _SY >> err.dat
grep ERROR checknfsymmy.out | grep -v _SY >> err.dat
awk '{ ZUM+=$3 } END { printf "%.12f\n", ZUM} ' err.dat

paste nearfieldX_yz.DAT  nearfieldX_yz.DAT.ref | awk '{ SUM+=($4-$8)*($4-$8)} END { printf "%.12f\n", SUM}'
paste nearfieldY_xy.DAT  nearfieldY_xy.DAT.ref | awk '{ SUM+=($4-$8)*($4-$8)} END { printf "%.12f\n", SUM}'

