#!/bin/sh
#
# Choose shell
#$ -S /bin/sh
# Work from the current working directory
#$ -cwd
# Name of the job
##$ -N ADDA
# Set requested execution time
#$ -l h_rt=4:00:00
# Set parallel environment and number of nodes 
#   (number of processors is a multiple of that number)
#$ -pe openmpi 8
# Merge stderr with stdout
#$ -j yes

PROG=/home/yurkin/fhgfs/adda/mpi/adda_mpi
# the following is specified outside
#ARGS=""

. /etc/profile.d/modules.sh
module add sge openmpi/gcc

#$ -v LD_LIBRARY_PATH

echo "Got $NSLOTS slots on nodes:"
cat $TMPDIR/machines

cmd="mpirun -np $NSLOTS $PROG $ARGS"
echo Will run: $cmd
$cmd
