#!/bin/bash
# Requires one argument - directory name
if [ $# -ne 1 ];then
  echo "ERROR: 1 argument required"
  exit 1
fi
# list of quantities to extract (each should be a single word)
quans="Cext"
# file in ADDA output to parse
qfile=CrossSec-Y
# variable that is changing between runs
var="Energy"

cd $1
if [ $? -ne 0 ]; then
  exit 1
fi
# initialize temporary files with results
rm -f tmp_*
echo $var > tmp_$var
tfiles=tmp_$var
for q in $quans; do
  echo $q > tmp_$q
  tfiles="$tfiles tmp_$q"
done
for i in `ls -d */ | sort -n`; do
  echo ${i%/} >> tmp_$var
  for q in $quans; do
    # The following assumes that q is a single word
	grep $q "${i}$qfile" | awk '{print $3}' >> tmp_$q
  done
done
paste $tfiles > "result.txt"
rm tmp_*
