#!/bin/bash
# A script for running ADDA simulations for a spectrum of wavelengths.
# First argument - full command line without refractive index and wavelength, e.g. "adda -grid 32"
#   the executable is either available from any path, the full path is provided, or the path is given relative to
#   the execution directory (see below) 
# Second argument - directory name, where runs are executed (generally, absolute path or path relative to the
#   script-execution path)
# Third argument - file with refractive index spectrum - columns with wavelength, Re(m), and Im(m)
if [[ $# -lt 4 || $# -gt 4 ]]; then
  echo "ERROR: 4 arguments required"
  exit 1
fi

cmdline="$1"
dir="$2"
# make absolute path out of $3 (if not already)
if [[ "$3" = /* ]]; then
  mfile="$3"
else 
  mfile="$(pwd)/$3"
fi
mh="$4"
# create working directory (if doesn't exist)
if [ ! -e "$dir" ]; then
  mkdir "$dir"
fi
cd "$dir"
while read ev mpre mpim elenergy; do
  lam=$(echo "scale = 8; 1239.8419 / $ev" | bc)
  mre=$(echo "scale = 8; $mpre / $mh" | bc)
  mim=$(echo "scale = 8; $mpim / $mh" | bc)
  #echo "$mpre $mpim"
  #echo "$mre $mim"
  #echo " "
  vari="-size 10 -lambda $lam -m $mre $mim -beam electron $elenergy 6 0 $mh -pol cm -sym enf -scat_matr none -dir $elenergy"
  $cmdline $vari
  #break
done < $mfile
