#!/bin/bash
# A script for running ADDA simulations for a spectrum of wavelengths.
# First argument - full command line without refractive index and wavelength, e.g. "adda -grid 32"
# Second argument - file with refractive index spectrum
# Requires one argument - Rp value (special values - cm and stat);
# if second argument is given - that is the wavelength; otherwise a loop is done
if [[ $# -lt 1 && $# -gt 2 ]];then
  echo "ERROR: 1 or 2 argument required"
  exit 1
fi

mfile=Ag.nk
minLam=${2:-300}
maxLam=${2:-500}
part="-shape sphere -size 20 -grid 100 -no_vol_cor"

if [ "$1" == "cm" ]; then
  int="-int poi -pol cm"
  name="$1"
elif [ "$1" == "stat" ]; then
  int="-int nloc 0 -pol cm"
  name="$1"
else
  Rp="$1"
  name="R${Rp}"
  int="-int nloc $Rp -pol nloc0 $Rp"
fi
const="$part $int"

dir="$name"
if [ ! -e $dir ]; then
  mkdir $dir
fi
cp batch $dir
cd $dir
echo $const > const.txt
while read lam mre mim; do
  if [[ "$lam" -ge "$minLam" && "$lam" -le "$maxLam" ]]; then
    vari="-lambda $lam -m $mre $mim -dir $lam"
    qsub -N ${name}_$lam -o $lam.o -v ARGS="$const $vari" batch
  fi
done < ../$mfile