#!/bin/bash

if [ -z "${ADDABIN}" ]; then
  export ADDABIN=$(readlink -f ../../../src/seq/adda)
fi
if [ ! -f "${ADDABIN}" ]; then
  echo "ERROR: No adda binary was found, as specified by environmental variable ADDABIN='${ADDABIN}'"
  exit 1
fi
if [ -z "${MPIEXEC}" ]; then
  which mpiexec > /dev/null 2>&1 # test availability of mpiexec
  if [ $? -eq 0 ]; then
    export MPIEXEC="mpiexec -n 4"
  else
    export MPIEXEC=""
  fi
fi

for j in *; do
  if [ -d $j ]; then 
  echo "*****************************"
  echo " Running Test " $j
  echo "*****************************"
  cd $j
  ./run
  cd ..
  fi
done
